const FETCH_FILMS_REQUEST = "FETCH_FILMS_REQUEST";
const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS";
const FETCH_FILMS_FAILURE = "FETCH_FILMS_FAILURE";

const FETCH_CHOSEN_FILM_REQUEST = "FETCH_CHOSEN_FILM_REQUEST";
const FETCH_CHOSEN_FILM_SUCCESS = "FETCH_CHOSEN_FILM_SUCCESS";
const FETCH_CHOSEN_FILM_FAILURE = "FETCH_CHOSEN_FILM_FAILURE";

export {
  FETCH_FILMS_REQUEST,
  FETCH_FILMS_SUCCESS,
  FETCH_FILMS_FAILURE,
  FETCH_CHOSEN_FILM_REQUEST,
  FETCH_CHOSEN_FILM_SUCCESS,
  FETCH_CHOSEN_FILM_FAILURE,
};
